# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YzmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='实例名称')),
                ('category', models.CharField(choices=[('1', '英文数字混合')], default='1', max_length=20, verbose_name='类别')),
                ('tag', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='4', max_length=20, verbose_name='验证码字符个数')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('image_url', models.CharField(max_length=300, verbose_name='URL链接')),
                ('img', models.ImageField(blank=True, default='', max_length=200, upload_to='caps/sites/', verbose_name='验证码图片(自动获取)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '验证码信息',
                'verbose_name_plural': '验证码信息',
            },
        ),
    ]
