# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzminfo', '0003_auto_20180412_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='nums',
            field=models.IntegerField(max_length=10, verbose_name='数据集大小'),
        ),
    ]
