# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzminfo', '0008_auto_20180413_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='path',
            field=models.FilePathField(allow_folders=True, path='media/data', verbose_name='数据集路径'),
        ),
    ]
