# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20180530_0204'),
        ('yzminfo', '0010_operationseri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationseri',
            name='yzmname',
        ),
        migrations.RemoveField(
            model_name='traindata',
            name='yzmname',
        ),
        migrations.RemoveField(
            model_name='yzmmodel',
            name='yzmname',
        ),
        migrations.AlterField(
            model_name='yzminfo',
            name='category',
            field=models.CharField(choices=[('1', '英文数字混合')], default='1', max_length=20, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='yzminfo',
            name='tag',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='4', max_length=20, verbose_name='验证码字符个数'),
        ),
        migrations.DeleteModel(
            name='OperationSeri',
        ),
        migrations.DeleteModel(
            name='TrainData',
        ),
        migrations.DeleteModel(
            name='YzmModel',
        ),
    ]
