# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yzm_info', '0001_initial'),
        ('spider_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredisctList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '正确'), ('2', '错误')], default='1', max_length=1, verbose_name='正误')),
                ('img', models.ImageField(upload_to='img/%Y/%m', verbose_name='验证码图片')),
                ('predict', models.CharField(max_length=50, verbose_name='预测结果')),
                ('desc', models.TextField(verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('spidername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzm_info.YzmInfo', verbose_name='爬虫')),
            ],
            options={
                'verbose_name': '预测结果列表',
                'verbose_name_plural': '预测结果列表',
            },
        ),
        migrations.CreateModel(
            name='SpiderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', '开始'), ('2', '结束')], default='2', max_length=1, verbose_name='状态')),
                ('desc', models.TextField(verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('spidername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider_monitor.SpiderInfo', verbose_name='实例名称')),
            ],
            options={
                'verbose_name': '爬虫状态',
                'verbose_name_plural': '爬虫状态',
            },
        ),
        migrations.RemoveField(
            model_name='monitorinfo',
            name='url',
        ),
        migrations.DeleteModel(
            name='MonitorInfo',
        ),
    ]
