# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_monitor', '0002_auto_20180412_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predisctlist',
            name='desc',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='spiderstatus',
            name='desc',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
