# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_monitor', '0006_auto_20180413_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderinfo',
            name='update_model',
            field=models.FileField(blank=True, default='', upload_to='mdoels/update/%Y/%m', verbose_name='支持模型文件上传'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='update_net',
            field=models.FileField(blank=True, default='', upload_to='mdoels/update/%Y/%m', verbose_name='支持网络文件上传'),
        ),
    ]
