# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_monitor', '0007_auto_20180414_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinfo',
            name='predict_nums',
            field=models.IntegerField(blank=True, default=0, verbose_name='识别次数'),
        ),
        migrations.AddField(
            model_name='spiderinfo',
            name='run_nums',
            field=models.IntegerField(blank=True, default=0, verbose_name='运行次数'),
        ),
        migrations.AddField(
            model_name='spiderinfo',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '正在运行'), ('2', '已经结束')], default='2', max_length=1, verbose_name='当前状态'),
        ),
    ]
