# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_monitor', '0008_auto_20180414_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinfo',
            name='pid',
            field=models.IntegerField(blank=True, default=0, verbose_name='当前运行的线程ID'),
        ),
    ]
