# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yzm_info', '0010_operationseri'),
        ('spider_monitor', '0010_auto_20180414_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='predisctlist',
            name='yzmname',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='yzm_info.YzmInfo', verbose_name='验证码名称'),
        ),
        migrations.AlterField(
            model_name='predisctlist',
            name='spidername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider_monitor.SpiderInfo', verbose_name='爬虫名称'),
        ),
    ]
