# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YzmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='实例名称')),
                ('category', models.CharField(choices=[('1', '纯英文字符'), ('2', '纯数字字符'), ('3', '英文数字混合')], default='1', max_length=20, verbose_name='类别')),
                ('tag', models.CharField(choices=[('1', '可切割'), ('2', '不可切割')], default='1', max_length=20, verbose_name='是否可切割')),
                ('desc', models.TextField(verbose_name='描述')),
                ('image_url', models.CharField(max_length=50, verbose_name='URL链接')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '验证码信息',
                'verbose_name_plural': '验证码信息',
            },
        ),
        migrations.CreateModel(
            name='YzmModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('desc', models.TextField(verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('yzmname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzm_info.YzmInfo', verbose_name='验证码信息')),
            ],
            options={
                'verbose_name': '验证码模型',
                'verbose_name_plural': '验证码模型',
            },
        ),
    ]
