# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzm_info', '0002_auto_20180412_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='yzminfo',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='yzmmodel',
            name='desc',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]
