# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-12 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzm_info', '0004_auto_20180412_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traindata',
            name='nums',
            field=models.IntegerField(verbose_name='数据集大小'),
        ),
    ]
