# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-06-04 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yzminfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='提交地址')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '提交地址',
                'verbose_name_plural': '提交地址',
            },
        ),
        migrations.CreateModel(
            name='CheckInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.CharField(max_length=100, verbose_name='验证属性')),
                ('value', models.CharField(max_length=100, verbose_name='验证属性值')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '验证值',
                'verbose_name_plural': '验证值',
            },
        ),
        migrations.CreateModel(
            name='PredisctList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '正确'), (0, '错误')], default=0, verbose_name='正误')),
                ('img', models.ImageField(upload_to='img/%Y/%m', verbose_name='验证码图片')),
                ('predict', models.CharField(max_length=50, verbose_name='预测结果')),
                ('desc', models.TextField(blank=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '预测结果列表',
                'verbose_name_plural': '预测结果列表',
            },
        ),
        migrations.CreateModel(
            name='SpiderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='实例名称')),
                ('desc', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(blank=True, choices=[('1', '正在运行'), ('2', '已经结束')], default='2', max_length=1, verbose_name='当前状态')),
                ('run_nums', models.IntegerField(blank=True, default=0, verbose_name='运行次数')),
                ('predict_nums', models.IntegerField(blank=True, default=0, verbose_name='识别次数')),
                ('needcheck', models.CharField(choices=[('1', '不需要验证'), ('2', '需要验证')], default='1', max_length=20, verbose_name='是否验证正确')),
                ('check', models.CharField(choices=[('1', '登录验证'), ('2', 'GET请求验证'), ('3', 'POST提交数据验证')], default='1', max_length=20, verbose_name='验证方式')),
                ('posturl', models.CharField(max_length=200, verbose_name='数据提交地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzminfo.YzmInfo', verbose_name='验证码名称')),
            ],
            options={
                'verbose_name': '爬虫信息',
                'verbose_name_plural': '爬虫信息',
            },
        ),
        migrations.AddField(
            model_name='predisctlist',
            name='spidername',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.SpiderInfo', verbose_name='爬虫名称'),
        ),
        migrations.AddField(
            model_name='predisctlist',
            name='yzmname',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='yzminfo.YzmInfo', verbose_name='验证码名称'),
        ),
        migrations.AddField(
            model_name='checkinfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.SpiderInfo', verbose_name='归属模型'),
        ),
        migrations.AddField(
            model_name='checkaddress',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.SpiderInfo', verbose_name='归属模型'),
        ),
    ]
