# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20180412_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinfo',
            name='update_model',
            field=models.FileField(default='', upload_to='update/%Y/%m', verbose_name='支持模型文件上传'),
        ),
        migrations.AddField(
            model_name='spiderstatus',
            name='ratio_nums',
            field=models.IntegerField(default=0, verbose_name='循环多少次'),
        ),
        migrations.AlterField(
            model_name='spiderinfo',
            name='yzmmodel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yzminfo.YzmModel', verbose_name='绑定模型'),
        ),
    ]
