# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-13 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180413_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderinfo',
            name='update_net',
            field=models.FileField(default='', upload_to='update/%Y/%m', verbose_name='支持网络文件上传'),
        ),
    ]
