# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-15 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20180415_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predisctlist',
            name='status',
            field=models.IntegerField(choices=[('1', '正确'), ('0', '错误')], default=0, verbose_name='正误'),
        ),
    ]
