# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-30 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_auto_20180530_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderinfo',
            name='update_model',
        ),
        migrations.RemoveField(
            model_name='spiderinfo',
            name='update_net',
        ),
    ]
